FROM openjdk:8-jdk-slim

ENV SPARK_VERSION=3.2.1

RUN apt-get update && \
    apt-get install -y curl tar procps && \
    curl -L https://archive.apache.org/dist/spark/spark-${SPARK_VERSION}/spark-${SPARK_VERSION}-bin-hadoop3.2.tgz \
    | tar -xz -C /opt && \
    mv /opt/spark-${SPARK_VERSION}-bin-hadoop3.2 /opt/spark

WORKDIR /opt/spark

EXPOSE 18080

CMD ["/opt/spark/sbin/start-history-server.sh"]
